Decision Tree Clasification

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
inputs = df.drop('Pclass', axis='columns')

In [12]:
target = df['Pclass']

In [13]:
inputs['Age'] = inputs['Age'].fillna(inputs['Age'].median())

In [14]:
from sklearn.preprocessing import LabelEncoder

le_sex = LabelEncoder()

In [15]:
inputs['Sex_n'] = le_sex.fit_transform(inputs['Sex'])

In [16]:
inputs_n = inputs[['Survived', 'Sex_n', 'Age', 'Fare']]
inputs_n

     Survived  Sex_n   Age     Fare
0           0      1  22.0   7.2500
1           1      0  38.0  71.2833
2           1      0  26.0   7.9250
3           1      0  35.0  53.1000
4           0      1  35.0   8.0500
..        ...    ...   ...      ...
886         0      1  27.0  13.0000
887         1      0  19.0  30.0000
888         0      0  28.0  23.4500
889         1      1  26.0  30.0000
890         0      1  32.0   7.7500

[891 rows x 4 columns]

In [17]:
target

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [18]:
from sklearn import tree

model = tree.DecisionTreeClassifier()

In [19]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [20]:
model.score(inputs_n, target)

0.9977553310886644

What Pclass is a Survived female, Age 38, Fare 71.28?

In [21]:
model.predict([[1, 0, 38, 71.28]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

What Pclass is a Not-survived male, Age 22, Fare 7.25?

In [22]:
model.predict([[0, 1, 22, 7.25]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([3])

What Pclass is a Survived male, Age 35, Fare 512?

In [23]:
model.predict([[1, 1, 35, 512]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [25]:
print("Model Accuracy:", round(model.score(inputs_n, target) * 100, 2), "%")

Model Accuracy: 99.78 %